require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0.0
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - config/
    - 'vendor/**/**/*'
    - bin/
    - app/assets/javascripts/

# Style

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

# Layout

Layout/TrailingEmptyLines:
  Enabled: true

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/IndentationStyle:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

# Metrics

Metrics/BlockNesting:
  Max: 4

Metrics/ClassLength:
  Max: 250

Metrics/MethodLength:
  Max: 15
  AllowedMethods: ['describe', 'context', 'feature', 'scenario', 'let']
  
Metrics/BlockLength:
  Max: 25
  AllowedMethods: ['describe', 'context', 'feature', 'scenario', 'let']

Metrics/ModuleLength:
  Max: 250

Layout/LineLength:
  Max: 100

# Rspec

RSpec/ContextWording:
  Enabled: false

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Max: 5
  
RSpec/EmptyLineAfterExample:
  Enabled: false

# Other

Bundler/OrderedGems:
  Enabled: true
  
RSpec/Capybara/CurrentPathExpectation:
  Enabled: false

RSpec/Capybara/FeatureMethods:
  Enabled: false
