# Source: https://github.com/marketplace/actions/rubocop-linter-action

name: "Rubocop"
on:
  pull_request:
    branches: [ "master", "development" ]
jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Rubocop
        uses: andrewmcodes/rubocop-linter-action@v3.0.0
        with:
          action_config_path: ".github/actions/config/rubocop.yml"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
